# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# include some helpers
rootDir = File.expand_path('../../')
require "#{rootDir}/vagrant/config.rb"
require "#{rootDir}/vagrant/shame.rb"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	cfg = getConfig()

	config.vm.box = "ubuntu/trusty64"
	config.vm.box_check_update = false

	config.ssh.forward_agent = true

	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", cfg[:memory]]
		vb.customize ["modifyvm", :id, "--cpus", cfg[:cores]]

		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.synced_folder ".", "/vagrant", id: "vagrant-root"

	# port forwarding
	config.vm.network :forwarded_port, guest: 80, host: 8000
	config.vm.network :private_network, ip: '192.168.10.10'

	config.vm.provision :puppet do |puppet|
	  puppet.manifests_path = "#{rootDir}/puppet/manifests"
		puppet.module_path = "#{rootDir}/puppet/modules"
	  puppet.manifest_file  = "web.pp"
	end

end

def configSetup(cfg)
	getInput("How many cores?", cfg, :cores, 1)
	getInput("How much memory?", cfg, :memory, 1024)
	getInputNumber("Port Offset?", cfg, :portOffset, 8000)
	getInput("VM workspace?", cfg, :ws, "~/workspace/web_mop",
		"This is a shared folder for applications source-code.")
end

# used by ./vagrant/config.rb to get config file name
# This is relative to the folder from where you run `vagrant up`
def getConfigFolder()
	File.expand_path('.')
end
