# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# include some helpers
rootDir = File.expand_path('../../')
require "#{rootDir}/vagrant/config.rb"
require "#{rootDir}/vagrant/shame.rb"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	cfg = getConfig()

	config.vm.box = "ubuntu/trusty64"
	config.vm.box_check_update = false

	config.vm.hostname = "go-app-1"

	config.ssh.forward_agent = true

	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", cfg[:memory]]
		vb.customize ["modifyvm", :id, "--cpus", cfg[:cores]]

		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.synced_folder ensureDir("#{rootDir}/src"), "/home/go_app/src/sample",
		:nfs => { :mount_options => ["dmode=777","fmode=777"] }

	# port forwarding
	config.vm.network :forwarded_port, guest: 8080, host: 8001
	config.vm.network :private_network, ip: '192.168.10.11'

	config.vm.provision :puppet do |puppet|
		puppet.facter = { "fqdn" => "local.app", "hostname" => "go-app-1" }
	  puppet.manifests_path = "#{rootDir}/puppet/manifests"
		puppet.module_path = "#{rootDir}/puppet/modules"
	  puppet.manifest_file  = "go_app.pp"
	end

	config.vm.provision "shell", path: "#{rootDir}/build.sh"
end

def configSetup(cfg)
	getInput("How many cores?", cfg, :cores, 1)
	getInput("How much memory?", cfg, :memory, 1024)
	getInputNumber("Port Offset?", cfg, :portOffset, 8000)
	getInput("VM workspace?", cfg, :ws, "~/workspace/go_app-1",
		"This is a shared folder for applications source-code.")
end

# used by ./vagrant/config.rb to get config file name
# This is relative to the folder from where you run `vagrant up`
def getConfigFolder()
	File.expand_path('.')
end
